name: plasticseg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  
  - python=3.10.14
  
  
  - numpy=1.26.4
  - scipy=1.14.0
  - pandas=2.2.2
  
  # ML
  - scikit-learn=1.5.0
  - scikit-image=0.23.2
  
  # Deep Learning (PyTorch with CUDA support)
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  
  # CV
  - opencv=4.10.0
  
  - git=2.40.1
  
  - matplotlib=3.8.4
  
  # Utilities
  - einops=0.8.0
  - spectral=0.23.1
  - requests=2.32.2
  - pyyaml=6.0.1
  
  # Development tools
  - ipython=8.25.0
  
  # Package management
  - pip
  
  # pip dependencies
  - pip:
    - torchaudio==2.1.2
    - torchvision==0.16.2
    - torchinfo==1.8.0
    - pillow==10.3.0
    - timm==1.0.9
    - tqdm==4.66.5
    - thop==0.1.1-2209072238
    - safetensors==0.4.5
    - huggingface-hub==0.25.1
    - h5py==3.14.0
    - hdf5storage==0.2.0
    - openpyxl==3.1.5
    - pyopengl==3.1.7
    - pyopengl-accelerate==3.1.7
    - wxpython==4.2.1   

#Execute the following command to create the environment:
#conda env create -f environment.yml

#To activate the environment:
#conda activate plasticseg